# Generated by Django 4.0.3 on 2022-03-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
